# Generated by Django 2.0.1 on 2018-02-18 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.User'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.User'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sis.User'),
        ),
    ]
