# Generated by Django 2.0.1 on 2018-02-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0003_auto_20180219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorprofile',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
