# Generated by Django 2.0.1 on 2018-03-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0005_auto_20180220_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('start', models.CharField(max_length=255, unique=True)),
                ('end', models.CharField(max_length=255, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Module')),
            ],
        ),
        migrations.RenameModel(
            old_name='Membership',
            new_name='UserModuleMembership',
        ),
    ]
