# Generated by Django 2.0.1 on 2018-03-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0007_auto_20180313_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
