# Generated by Django 2.0.1 on 2018-03-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0011_module_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='start',
            field=models.DateField(),
        ),
    ]
