# Generated by Django 2.0.1 on 2018-03-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0012_auto_20180317_2028'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermodulemembership',
            unique_together={('user', 'module')},
        ),
        migrations.AlterIndexTogether(
            name='usermodulemembership',
            index_together={('user', 'module')},
        ),
    ]
