# Generated by Django 2.0.1 on 2018-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0013_auto_20180317_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.CharField(default='unspecified', max_length=255),
        ),
    ]
