# Generated by Django 2.0.1 on 2018-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0014_auto_20180319_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
