# Generated by Django 2.0.1 on 2018-03-27 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0015_auto_20180319_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseworkMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('completed', models.BooleanField()),
                ('priority', models.CharField(default='LEVEL 3', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
