# Generated by Django 2.0.1 on 2018-03-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0016_usercourseworkmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseworkmembership',
            name='coursework',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sis.Coursework'),
        ),
    ]
