# Generated by Django 2.0.1 on 2018-03-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0019_auto_20180329_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseworkmembership',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='usercourseworkmembership',
            name='completed_25_percent',
        ),
        migrations.RemoveField(
            model_name='usercourseworkmembership',
            name='completed_50_percent',
        ),
        migrations.RemoveField(
            model_name='usercourseworkmembership',
            name='completed_75_percent',
        ),
        migrations.AddField(
            model_name='usercourseworkmembership',
            name='percentage',
            field=models.IntegerField(choices=[(0, '0'), (25, '25'), (50, '50'), (75, '75'), (100, '100')], default=0),
        ),
    ]
