# Generated by Django 2.0.1 on 2018-03-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0020_auto_20180329_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseworkmembership',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
