# Generated by Django 2.0.1 on 2018-04-11 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0022_auto_20180329_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usercourseworkmembership',
            name='percentage',
            field=models.IntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, 'Done')], default=0),
        ),
    ]
