# Generated by Django 2.0.1 on 2018-04-11 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0023_auto_20180411_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='coursework_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='module_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
