# Generated by Django 2.0.1 on 2018-04-11 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0024_auto_20180411_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='coursework_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='module_id',
        ),
    ]
