# Generated by Django 2.0.1 on 2018-04-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0025_auto_20180411_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseworkmembership',
            name='coursework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sis.Coursework'),
        ),
    ]
