# Generated by Django 2.0.1 on 2018-04-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0027_coursework_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='color',
            field=models.CharField(default='#FF0000', max_length=255),
        ),
    ]
