# Generated by Django 2.0.1 on 2018-04-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0028_auto_20180414_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='color',
            field=models.CharField(default='#f3452c', max_length=255),
        ),
    ]
