# Generated by Django 2.0.1 on 2018-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0029_auto_20180414_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourseworkmembership',
            name='priority',
        ),
        migrations.AlterField(
            model_name='coursework',
            name='color',
            field=models.CharField(default='#948b79', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
