# Generated by Django 2.0.1 on 2018-04-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis', '0030_auto_20180423_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
